export const PROJECT_REPOSITORY = 'PROJECT_REPOSITORY';
export const PROJECT_SLUG_SERVICE = 'PROJECT_SLUG_SERVICE';
export const PROJECT_ANALYTICS_SERVICE = 'PROJECT_ANALYTICS_SERVICE';
export const PROJECT_THUMBNAIL_SERVICE = 'PROJECT_THUMBNAIL_SERVICE';
